title: Brandon Murray
email: hello@brandonmurray.ca
description: >-
  Design portfolio of Canadian freelance designer Brandon Murray.
  Showcasing featured work from past clients and sharing a bit
  about the design process.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"